// SPDX-FileCopyrightText: 2026 Milos Vasic
// SPDX-License-Identifier: Apache-2.0

// Code generated for HXC-243 by patch_banks.py's decision log,
// diffed against the pre-fix git HEAD content of the 7 affected
// bank files. DO NOT EDIT BY HAND — regenerate from that diff if
// the bank files change.

package autonomous

// hxc243AssignedChecks enumerates every http: step this fix gave an
// explicit expect_status to (derived by diffing the 7 patched bank
// files against their pre-fix git HEAD content — see HXC-243). Each
// row is independently proven capable of failing (golden-bad) and
// capable of passing (golden-good) below — not a sample, every one.
var hxc243AssignedChecks = []hxc243Check{
	{File: "admin-operations.json", CaseID: "ADM-002", StepName: "Request system info as admin", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-003", StepName: "Request system info as admin", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-005", StepName: "Verify user exists", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-007", StepName: "Verify deletion", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-009", StepName: "Verify role change", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-012", StepName: "Monitor scan progress", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-013", StepName: "Verify root added", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-014", StepName: "Verify removal", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-019", StepName: "Request error logs only", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-019", StepName: "Request warning logs", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-020", StepName: "Request logs for last hour", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-021", StepName: "Collect logs again", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-022", StepName: "Verify change", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-026", StepName: "Request health check", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-029", StepName: "Check metrics", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-030", StepName: "Request metrics", ExpectStatus: 200},
	{File: "admin-operations.json", CaseID: "ADM-044", StepName: "Check database pool config", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-001", StepName: "Verify entity exists", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-002", StepName: "Verify entity type", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-003", StepName: "Verify entity metadata", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-004", StepName: "Verify entity", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-005", StepName: "Verify entity", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-006", StepName: "Verify entity", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-007", StepName: "Verify entity", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-008", StepName: "Verify entity", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-009", StepName: "Verify entity", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-010", StepName: "Verify parent link", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-011", StepName: "Verify parent link", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-012", StepName: "Verify no entity created", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-014", StepName: "Query hierarchy", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-014", StepName: "Query season children", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-015", StepName: "Traverse hierarchy", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-016", StepName: "Query children", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-017", StepName: "Query show children", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-018", StepName: "Query season children", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-019", StepName: "Search by title", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-020", StepName: "Filter by type movie", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-021", StepName: "Filter by year 2020", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-022", StepName: "Search title+type", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-024", StepName: "Search lowercase", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-024", StepName: "Search uppercase", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-028", StepName: "Verify update", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-029", StepName: "Verify metadata", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-030", StepName: "Verify year", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-033", StepName: "Verify outcome", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-035", StepName: "Browse first page", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-036", StepName: "Request page 2", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-038", StepName: "Request sorted by title ascending", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-039", StepName: "Sort by created_at descending", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-040", StepName: "Filter by movie", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-041", StepName: "Filter by book", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-042", StepName: "Filter by game", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-043", StepName: "Filter by tv_show", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-045", StepName: "Request statistics", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-046", StepName: "Request entity count", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-048", StepName: "Verify association", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-049", StepName: "Verify all files", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-050", StepName: "Verify removal", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-051", StepName: "Query collection", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-052", StepName: "Verify removal", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-057", StepName: "Verify entities created", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-058", StepName: "Verify parsed entity", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-059", StepName: "Verify hierarchy", ExpectStatus: 200},
	{File: "entity-management.json", CaseID: "ENT-060", StepName: "Verify single entity", ExpectStatus: 200},
	{File: "full-qa-android.json", CaseID: "FQA-AND-150", StepName: "Trigger SMB reconnect", ExpectStatus: 200},
	{File: "full-qa-android.json", CaseID: "FQA-AND-165", StepName: "Update profile", ExpectStatus: 200},
	{File: "full-qa-api.json", CaseID: "FQA-API-025", StepName: "Request with Accept-Encoding: br", ExpectStatus: 200},
	{File: "full-qa-api.json", CaseID: "FQA-API-025", StepName: "Request with Accept-Encoding: gzip", ExpectStatus: 200},
	{File: "full-qa-api.json", CaseID: "FQA-API-026", StepName: "Inspect response headers from health", ExpectStatus: 200},
	{File: "full-qa-api.json", CaseID: "FQA-API-027", StepName: "Send any request", ExpectStatus: 200},
	{File: "full-qa-api.json", CaseID: "FQA-API-052", StepName: "Queue a scan and get job ID", ExpectStatus: 200},
	{File: "full-qa-api.json", CaseID: "FQA-API-055", StepName: "Queue scan", ExpectStatus: 200},
	{File: "full-qa-api.json", CaseID: "FQA-API-055", StepName: "Poll scan status 3 times", ExpectStatus: 200},
	{File: "full-qa-api.json", CaseID: "FQA-API-057", StepName: "Queue scan for empty root", ExpectStatus: 200},
	{File: "full-qa-api.json", CaseID: "FQA-API-070", StepName: "Queue first scan", ExpectStatus: 200},
	{File: "full-qa-api.json", CaseID: "FQA-API-175", StepName: "Verify both exist", ExpectStatus: 200},
	{File: "full-qa-api.json", CaseID: "FQA-API-208", StepName: "Verify both in list", ExpectStatus: 200},
	{File: "full-qa-api.json", CaseID: "FQA-API-209", StepName: "Create playlist with items", ExpectStatus: 201},
	{File: "full-qa-api.json", CaseID: "FQA-API-233", StepName: "Queue a scan", ExpectStatus: 200},
	{File: "full-qa-api.json", CaseID: "FQA-API-236", StepName: "Check metrics", ExpectStatus: 200},
	{File: "full-qa-cross-platform.json", CaseID: "FQA-XP-002", StepName: "Get media count from API", ExpectStatus: 200},
	{File: "full-qa-cross-platform.json", CaseID: "FQA-XP-003", StepName: "Search 'Matrix' via API", ExpectStatus: 200},
	{File: "full-qa-cross-platform.json", CaseID: "FQA-XP-004", StepName: "Verify via API", ExpectStatus: 200},
	{File: "full-qa-cross-platform.json", CaseID: "FQA-XP-006", StepName: "List media types via API", ExpectStatus: 200},
	{File: "full-qa-cross-platform.json", CaseID: "FQA-XP-008", StepName: "Get movie entity via API", ExpectStatus: 200},
	{File: "full-qa-cross-platform.json", CaseID: "FQA-XP-009", StepName: "Browse Cyrillic path via API", ExpectStatus: 200},
	{File: "full-qa-cross-platform.json", CaseID: "FQA-XP-010", StepName: "Search 'Музика' via API", ExpectStatus: 200},
	{File: "full-qa-cross-platform.json", CaseID: "FQA-XP-013", StepName: "List entities via API", ExpectStatus: 200},
	{File: "full-qa-cross-platform.json", CaseID: "FQA-XP-015", StepName: "Verify via API", ExpectStatus: 200},
	{File: "full-qa-cross-platform.json", CaseID: "FQA-XP-019", StepName: "Check API version", ExpectStatus: 200},
	{File: "full-qa-cross-platform.json", CaseID: "FQA-XP-020", StepName: "Verify all favorites from API", ExpectStatus: 200},
	{File: "performance-validation.json", CaseID: "PERF-015", StepName: "Request large page", ExpectStatus: 200},
	{File: "performance-validation.json", CaseID: "PERF-022", StepName: "Request JS bundle", ExpectStatus: 200},
	{File: "performance-validation.json", CaseID: "PERF-022", StepName: "Request CSS", ExpectStatus: 200},
	{File: "performance-validation.json", CaseID: "PERF-024", StepName: "First request", ExpectStatus: 200},
	{File: "performance-validation.json", CaseID: "PERF-024", StepName: "Second identical request", ExpectStatus: 200},
	{File: "performance-validation.json", CaseID: "PERF-025", StepName: "Request without compression", ExpectStatus: 200},
	{File: "performance-validation.json", CaseID: "PERF-025", StepName: "Request with Brotli", ExpectStatus: 200},
	{File: "performance-validation.json", CaseID: "PERF-026", StepName: "Request with gzip only", ExpectStatus: 200},
	{File: "performance-validation.json", CaseID: "PERF-030", StepName: "Record baseline goroutine count", ExpectStatus: 200},
	{File: "performance-validation.json", CaseID: "PERF-030", StepName: "Check goroutine count", ExpectStatus: 200},
	{File: "performance-validation.json", CaseID: "PERF-031", StepName: "Search by indexed field", ExpectStatus: 200},
	{File: "performance-validation.json", CaseID: "PERF-031", StepName: "Search by title", ExpectStatus: 200},
	{File: "performance-validation.json", CaseID: "PERF-037", StepName: "Verify all entities created", ExpectStatus: 200},
	{File: "performance-validation.json", CaseID: "PERF-053", StepName: "Measure cold cache query", ExpectStatus: 200},
	{File: "performance-validation.json", CaseID: "PERF-053", StepName: "Measure warm cache query", ExpectStatus: 200},
	{File: "security-validation.json", CaseID: "SEC-009", StepName: "Verify table intact", ExpectStatus: 200},
	{File: "security-validation.json", CaseID: "SEC-012", StepName: "Retrieve entity", ExpectStatus: 200},
	{File: "security-validation.json", CaseID: "SEC-013", StepName: "Search with script payload", ExpectStatus: 200},
	{File: "security-validation.json", CaseID: "SEC-029", StepName: "Login from client A", ExpectStatus: 200},
	{File: "security-validation.json", CaseID: "SEC-029", StepName: "Login from client B", ExpectStatus: 200},
	{File: "security-validation.json", CaseID: "SEC-032", StepName: "List users", ExpectStatus: 200},
	{File: "security-validation.json", CaseID: "SEC-032", StepName: "Get single user", ExpectStatus: 200},
	{File: "security-validation.json", CaseID: "SEC-035", StepName: "Request with Brotli accept", ExpectStatus: 200},
	{File: "security-validation.json", CaseID: "SEC-036", StepName: "Check response headers", ExpectStatus: 200},
	{File: "security-validation.json", CaseID: "SEC-038", StepName: "Check Server header", ExpectStatus: 200},
	{File: "security-validation.json", CaseID: "SEC-040", StepName: "Retrieve and verify", ExpectStatus: 200},
	{File: "security-validation.json", CaseID: "SEC-048", StepName: "Time login with valid username", ExpectStatus: 200},
	{File: "security-validation.json", CaseID: "SEC-055", StepName: "Login via web UI", ExpectStatus: 200},
}
